### ISSUE TITLE
Issues bij contacten details en aanpassen van contacten

### ISSUE THREAD

**Issue by RickSchoot** [roodkapje/CrmAppSchool#23]
Contacten Details:
1. Bij omschrijving komt nooit iets te staan

Aanpassen contact:
1. Leeg veld onderin doet niets?
2 Misschien de optie om de soort contact aan te passen.

**Comment by roodkapje** [comment]
Contacten details:
1 fixxed

Aanpassen contact:
1 fixxed

**Comment by roodkapje** [comment]
2 ook klaar.
